name: Context Demo

on: workflow_dispatch 

jobs:
  print-some-stuff:
    runs-on: windows-latest
    steps:
      -   name: print some stuff
          run:  |
              echo "Hello world from workflow"
              echo "Repository:: ${{ github.action }}"
              

  
